
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Common
{
public partial class TbConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Config> _dataMap;
    private readonly System.Collections.Generic.List<Config> _dataList;
    
    public TbConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Config>();
        _dataList = new System.Collections.Generic.List<Config>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Config _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Config.DeserializeConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.PlayerMaxLevel, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Config> DataMap => _dataMap;
    public System.Collections.Generic.List<Config> DataList => _dataList;

    public Config GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Config Get(int key) => _dataMap[key];
    public Config this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

