
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Config : Luban.BeanBase
{
    public Config(JSONNode _buf) 
    {
        { if(!_buf["playerMaxLevel"].IsNumber) { throw new SerializationException(); }  PlayerMaxLevel = _buf["playerMaxLevel"]; }
        { if(!_buf["testData"].IsNumber) { throw new SerializationException(); }  TestData = _buf["testData"]; }
    }

    public static Config DeserializeConfig(JSONNode _buf)
    {
        return new Config(_buf);
    }

    /// <summary>
    /// 玩家最大等级
    /// </summary>
    public readonly int PlayerMaxLevel;
    /// <summary>
    /// 测试数据
    /// </summary>
    public readonly float TestData;
   
    public const int __ID__ = 2024042338;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "playerMaxLevel:" + PlayerMaxLevel + ","
        + "testData:" + TestData + ","
        + "}";
    }
}

}
