fileFormatVersion: 2
guid: 74f140c827788b64ebde10a2197d3c0b
DefaultImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
AssetOrigin:
  serializedVersion: 1
  productId: 287711
  packageName: 'FishNet Pro: Networking Evolved'
  packageVersion: 4.4.6R Pro
  assetPath: Assets/FishNet/Plugins/Edgegap/Editor/Dockerfile
  uploadId: 694075
